### PR TITLE
Use reduction for ITT instead of typed conversion

### PR DESCRIPTION
**Pull request by TheoWinterhalter**
This branch uses reduction as a base for conversion in ITT. This brings ITT closer to TemplateCoq. We hope for this branch to reduce the number of axioms used in typing (should be 1).

Additionally, we managed to put the typing judgments in Prop, meaning everything computes, including the inductive types and constructors (note: we still do not handle Case in this branch).

What remains to do in this branch (although most of them weren't handled in the `reflection` branch anyway):

- [x] Prove uniqueness of typing for CongProd (using context conversion)
- [x] Prove uniqueness of typing for HeqTypeEq (it requires further annotation)
- [x] Prove context conversion
- [x] Prove subject reduction
- [x] Prove typing modulo α-renaming
- [x] Have all examples compute

### CODE REVIEW

**Comment by mattam82** [comment]
I'm not sure I understand why you need to put the typing judgments in Prop? Is it to make the extracted translation compute?

**Comment by TheoWinterhalter** [comment]
Yes, even the non extracted version. It syntactically forces us to postpone matching on proof-terms (that might use axioms).

**Comment by mattam82** [comment]
I see. So you could go back to Type at the end. Otherwise you won't be able to write the ITT -> TemplateCoq translation right? Or is that one requiring only induction on terms as it is more syntax-directed?

**Comment by TheoWinterhalter** [comment]
The last translation still works, it only uses the ITT term and not its derivation.
The translation of vec bool which didn't work before now computes.
However I just found out that `vec bool zero` still doesn't terminate... Maybe I should put `Qed` instead of `Defined` for the proofs that land in `Prop`?

**Comment by TheoWinterhalter** [comment]
There are no more holes (no axiom except transitivity of conversion), so I merge.

**Pull request merged**
